//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GymKW.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubscriptionType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SubscriptionType()
        {
            this.Subscription = new HashSet<Subscription>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public bool GroupClasses { get; set; }
        public bool PersonalCoach { get; set; }
        public bool FullTimeAccess { get; set; }
        public bool SpaServices { get; set; }
        public bool IndividualTrainingProgramm { get; set; }
        public bool WiFiAccess { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Subscription> Subscription { get; set; }
    }
}
